data:
  path: /tmp/math_Qwen2-7B-Instruct.parquet
  output_path: /tmp/math_Qwen2-7B-Instruct_new.parquet
  prompt_key: prompt
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model