### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: train_data
template: qwen
cutoff_len: 16384
# max_samples: 1000
overwrite_cache: False
preprocessing_num_workers: 16

### output
output_dir: saves/codev-r1-distill/full/sft
logging_steps: 20
save_steps: 500
plot_loss: True
overwrite_output_dir: False

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
seed: 42
optim: adamw_torch
packing: true
flash_attn: fa2
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
